/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rpsGameSol from "./RPSGame.sol";
export type { rpsGameSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GameToken } from "./GameToken";
export type { GameTokenUpgradeable } from "./GameTokenUpgradeable";
export type { YieldStaker } from "./YieldStaker";
